name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bamtools=2.5.1
  - bcftools=1.9
  - bioconductor-apeglm=1.4.1
  - bioconductor-deseq2=1.22.1
  - bioconductor-edger=3.26.0
  - bioconductor-limma=3.40.0
  - biopython
  - fastqc=0.11.8
  - igvtools=2.5.3
  - perl=5.26.2
  - r-base=3.5.1
  - r-colorspace=1.4_1
  - r-getopt=1.20.3
  - r-ggplot2=3.2.0
  - r-gplots=3.0.1.1
  - r-optparse=1.6.2
  - r-rcolorbrewer=1.1_2
  - r-rcurl=1.95_4.12
  - r-reshape2=1.4.3
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - readline=8.0
  - rseqc=3.0.0
  - samtools=1.9
  - sra-tools=2.10.0
  - star=2.7.3a
  - tpmcalculator=0.0.3
  - trimmomatic=0.39
  - ucsc-gtftogenepred=377
  - ucsc-genepredtobed=377
