name: jupyter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.76
  - cwl_runner=1.0
  - cwltool=3.0.20200317203547
  - idr=2.0.4.2
  - jupyter=1.0.0
  - jupyterngsplugin=0.0.13a3
  - matplotlib=3.2.1
  - networkx=2.4
  - nodejs=13.13.0
  - numpy=1.18.4
  - pandas=1.0.3
  - parallel=20200322
  - perl=5.26.2
  - perl-uri=1.76
  - perl-xml-libxml=2.0132
  - python=3.7.6
  - python-goenrichment=0.0.10a3
  - scipy=1.4.1
  - seaborn=0.10.1
  - statsmodels=0.11.1
  - unzip=6.0
  - wand=0.5.6
  - xmltodict=0.12.0
