name: transannot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - awscli=1.18.81
  - blast=2.9.0
  - transdecoder=5.5.0
  - biopython=1.76
  - cwl_runner=1.0
  - cwltool=3.0.20200530110633
  - matplotlib=3.2.1
  - networkx=2.4
  - numpy=1.18.5
  - nodejs=14.4.0
  - pandas=1.0.4
  - parallel=20200522
  - samtools=1.10
  - sra-tools=2.10.7
  - star=2.7.5a
