name: chipseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - bedtools=2.28.0
  - bioconductor-apeglm=1.4.1
  - bioconductor-biomart=2.38.0
  - bioconductor-chipqc=1.18.2
  - bioconductor-deseq2=1.22.1
  - bioconductor-diffbind=2.10.0
  - bioconductor-edger=3.24.3
  - bioconductor-limma=3.38.3
  - bwa=0.7.17
  - fastqc=0.11.8
  - homer=4.10
  - igvtools=2.5.3
  - macs2=2.1.2
  - phantompeakqualtools=1.2
  - r-base=3.5.1
  - r-colorspace=1.4_1
  - r-getopt=1.20.3
  - r-ggplot2=3.2.0
  - r-gplots=3.0.1.1
  - r-optparse=1.6.2
  - r-rcolorbrewer=1.1_2
  - r-rcurl=1.95_4.12
  - r-reshape2=1.4.3
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - rseqc=2.6.4
  - samtools=1.9
  - sra-tools=2.10.0
  - trimmomatic=0.39
