name: transannot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - awscli
  - blast=2.9.0
  - transdecoder=5.5.0
  - biopython=1.74
  - cwl_runner=1.0
  - cwltool=1.0.20190228155703
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - networkx=2.4
  - nodejs=12.3.0
  - pandas=0.25.0
  - parallel=20200122
  - samtools
  - sra-tools
  - star
