name: chipexo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bamscale=0.0.3
  - bcftools=1.9
  - bedtools=2.28.0
  - bwa=0.7.17
  - fastqc=0.11.8
  - gffread=0.11.4
  - homer=4.10
  - mace=1.2
  - meme=5.0.5
  - phantompeakqualtools=1.2
  - r-base=3.5.1
  - r-colorspace=1.4_1
  - r-getopt=1.20.3
  - r-ggplot2=3.2.0
  - r-gplots=3.0.1.1
  - r-optparse=1.6.2
  - r-rcolorbrewer=1.1_2
  - r-rcurl=1.95_4.12
  - r-reshape2=1.4.3
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - rseqc=2.6.4
  - samtools=1.9
  - sra-tools=2.10.0
  - trimmomatic=0.39
  - ucsc-gtftogenepred=377
  - ucsc-genepredtobed=377
