name: jupyter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7
  - biopython=1.74
  - cwl_runner=1.0
  - cwltool=1.0.20190228155703
  - jupyter=1.0.0
  - jupyterngsplugin=0.0.13a3
  - idr=2.0.4.2
  - matplotlib=3.1.1
  - networkx=2.3
  - nodejs=12.3.0
  - pandas=0.25.0
  - parallel=20200122
  - perl=5.26.2
  - perl-uri=1.76
  - perl-xml-libxml=2.0132
  - python-goenrichment=0.0.10a3
  - scipy=1.3.0
  - seaborn=0.9.0
  - unzip=6.0
  - xmltodict=0.12.0
